### ISSUE TITLE
api2二次验证返回来的string会被转义成 "{\"status\":\"success\",\"version\":\"4.0\"}"

### ISSUE THREAD

**Issue by axios94** [GeeTeam/gt3-android-sdk#10]
/**
             * 验证全部走完的回调，result为验证后的数据
             */
            @Override
            public void gt3DialogSuccessResult(String result) {
                if(!TextUtils.isEmpty(result)) {
                    try {
                        JSONObject jobj = new JSONObject(result);
                        String sta = jobj.getString("status");
                        if ("success".equals(sta)) {
                            gt3GeetestUtils.gt3TestFinish();
                        } else {
                            gt3GeetestUtils.gt3TestClose();
                        }
                    } catch (JSONException e) {
                        e.printStackTrace();
                    }
                }else
                {
                    gt3GeetestUtils.gt3TestClose();
                }
            }

JSONObject jobj = new JSONObject(result);
这一句就会报错

org.json.JSONException: Value {'status':'success','version':'4.0'} of type java.lang.String cannot be converted to JSONObject

**Comment by YanLingHao** [comment]
gt3DialogSuccessResult这个接口回调会返回与验证码交互后二次验证的数据 本次数据是取决于您的api2的配置 查看下您那边服务器返回的数据是否正常 根据您那边的服务器返回的数据 判断是否验证成功 成功调用gt3GeetestUtils.gt3TestFinish(); 失败调用gt3GeetestUtils.gt3TestClose();即可，以上只是针对极验服务器返回数据写的一个例子。

**Comment by axios94** [comment]
好的，感谢你的快速回复。目前已经改为在后台做处理了。
