### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by LostKe** [GeeTeam/gt3-android-sdk#11]
项目下载下来,编译出现如下错误

/Users/dev/git/gt3-android-sdk/app/build/intermediates/exploded-aar/gt3geetest_sdk/res/values-zh-rHK/values-zh-rHK.xml
Error:(3, 5) Attribute "gt3gifViewStyle" has already been defined
Error:(6, 5) Attribute "gt3gif" has already been defined
Error:(6, 5) Attribute "gt3paused" has already been defined
/Users/dev/git/gt3-android-sdk/app/build/intermediates/exploded-aar/gt3geetest_sdk/res/values-zh-rMO/values-zh-rMO.xml
Error:(3, 5) Attribute "gt3gifViewStyle" has already been defined
Error:(6, 5) Attribute "gt3gif" has already been defined
Error:(6, 5) Attribute "gt3paused" has already been defined
/Users/dev/git/gt3-android-sdk/app/build/intermediates/exploded-aar/gt3geetest_sdk/res/values-zh-rTW/values-zh-rTW.xml
Error:(3, 5) Attribute "gt3gifViewStyle" has already been defined
Error:(6, 5) Attribute "gt3gif" has already been defined
Error:(6, 5) Attribute "gt3paused" has already been defined
/Users/dev/git/gt3-android-sdk/app/build/intermediates/res/merged/debug/values/values.xml
Error:(105) Attribute "gt3gifViewStyle" has already been defined
Error:(106) Attribute "gt3gif" has already been defined
Error:(106) Attribute "gt3paused" has already been defined
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/dev/tools/android-env/android-sdk-macosx/build-tools/23.0.3/aapt'' finished with non-zero exit value 1

**Comment by YanLingHao** [comment]
错误提示是values下存在重名的属性名，您检查下您values下attrs.xml文件中是否有存在gt3gifViewStyle，gt3gif，gt3paused这三个属性名，如果存在 修改属性名即可

**Comment by LostKe** [comment]
sdk升级到25就好了

**Comment by liaozan** [comment]
换成25还是报错编译不过，同样的报错，怎么破？
