### ISSUE TITLE
设置是否可以点击Dialog灰色区域关闭验证码

### ISSUE THREAD

**Issue by hlla** [GeeTeam/gt3-android-sdk#16]
版本3.5.7.4Demo中
MainBindActivity的设置是否可以点击Dialog灰色区域关闭验证码方法不起作用:
gt3GeetestUtils.setDialogTouch(false);

**Comment by songsongbrother** [comment]
请将gt3GeetestUtils.setDialogTouch(false);调整到gt3GeetestUtils.getGeetest()方法的后面

**Comment by hlla** [comment]
是的,放到后边就可以了,谢谢大佬
