### ISSUE TITLE
关于SDK使用的几个问题

### ISSUE THREAD

**Issue by ciscolxh** [GeeTeam/gt3-android-sdk#17]
1.国际化的语言参数是什么？参数对应表好像没有介绍好像接口文档并没有介绍。
2.极验证验证失败的弹窗文字能不能自己定义

**Comment by guxiaonian** [comment]
1:""--国语，"en"--英文，"id"--印尼语，"ja"--日文 文档下面的Q&A下面第7个。
2：现在弹窗文字不能自定义，额外需求可以联系本公司相关人员。
