### ISSUE TITLE
Javadoc缺失

### ISSUE THREAD

**Issue by lby1992** [GeeTeam/gt3-android-sdk#21]
找不到公开api的java文档注释，能否提供？

**Comment by YuanchaoLi** [comment]
调用极验证后，会导致应用内设置的多语言环境重置为中文。

**Comment by guxiaonian** [comment]
@lby1992 javaDoc参考https://docs.geetest.com/install/deploy/server/java
@YuanchaoLi 这边能描述的详细一点吗，应用内的多语言？

**Comment by lby1992** [comment]
@guxiaonian ok，thanks
