### ISSUE TITLE
极验证导致多语言适配混乱问题

### ISSUE THREAD

**Issue by YuanchaoLi** [GeeTeam/gt3-android-sdk#22]
调用极验证后，会导致应用内设置的多语言环境重置为中文。

**Comment by guxiaonian** [comment]
这边能描述的详细一点吗，应用内的多语言？

**Comment by YuanchaoLi** [comment]
app国际化，配置多语言参数了。调起极验证后，会把应用内语言环境重置为中文。

**Comment by YuanchaoLi** [comment]
举例：
进入一个Activity，配置语言环境，getResources().updateConfiguration(configuration, displayMetrics);
但是调起极验证后，会发现configuration被重置为中文。

**Comment by guxiaonian** [comment]
sdk内部并没有配置相关语言，只是获取local的语言

**Comment by YuanchaoLi** [comment]
你可以写个demo测试一下，调起极验证后，确实会影响到configuration语言的设置。

**Comment by guxiaonian** [comment]
我demo试了没问题，验证并不会改设置的语言

**Comment by YuanchaoLi** [comment]
我拿你们最新的SDK做测试，就存在这个问题。

**Comment by YuanchaoLi** [comment]
不信的话，方便给个邮箱，把demo发你跑一下。

**Comment by guxiaonian** [comment]
在onDialogReady接口返回中添加
 MultiLanguageManager.checkLanguage(MainBindActivity.this);可以解决
现在还在排查问题来源
