### ISSUE TITLE
fragment 中使用无法显示

### ISSUE THREAD

**Issue by Jastyle** [GeeTeam/gt3-android-sdk#5]
在activity的oncreate周期中初始化正常，fragment中初始化无法显示，需要在fragment哪个生命周期初始化？

**Comment by guxiaonian** [comment]
这个现在还没有兼容在fragement初始化，主要现在传的是activity.class，当然这一块也可以优化

**Comment by Jastyle** [comment]
什么时候打算支持fragment，有计划吗?

**Comment by guxiaonian** [comment]
您好，刚才测了一下，fragement里面传getActivity()这个上下文是可以运行的啊
