### ISSUE TITLE
问题描述：我们服务端配置，第一个url地址返回的json嵌套格式数据 Jsonobject无法解析，应该用JSONArray解析，望修复；

### ISSUE THREAD

**Issue by ywqyunshan** [GeeTeam/gt3-android-sdk#8]
问题描述：我们服务端配置，第一个url地址返回的json嵌套格式数据 Jsonobject无法解析，应该用JSONArray解析，望修复；
源码问题地址：public JSONObject check2Server(Map<String, String> headers) {
        try {
            String e = this.readContentFromGet(this.captchaURL, headers);
            if(e.length() > 0) {
                Log.i("Geetest", "checkServer: " + e);
                JSONObject config = new JSONObject(e);
                this.geetestbean.setSuccess(config.getInt("success"));
                this.geetestbean.setChallenge(config.getString("challenge"));
                this.geetestbean.setGt(config.getString("gt"));
                return config;
            }
        } catch (Exception var4) {
            if(this.geetestListener != null) {
                this.geetestListener.receiveInvalidParameters();
            }

            var4.printStackTrace();
        }

        return null;
    }

**Comment by YanLingHao** [comment]
由于使用人群过多，数据格式大有不同，所以SDK决定由用户去适应，同时我们也可以把api1交给客户去自定义，参考最新的文档
