### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by gpw828** [GeeTeam/gt3-android-sdk#9]
private final Context context;
    private static final List<String> list = new ArrayList();
    private Map map = new HashMap();
    private long time;
    private boolean canAddMsg = true;

    public static GT3LifecycleCallBacks getInstance(Context context) {
        if(mWeLifecycleCallBacks == null) {
            mWeLifecycleCallBacks = new GT3LifecycleCallBacks(context);
        }

        return mWeLifecycleCallBacks;
    }
单例泄漏了context

**Comment by YanLingHao** [comment]
目前版本已经优化，加了守护锁
